/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#fbf8ff",
        "on-surface-variant": "#424656",
        "on-secondary": "#ffffff",
        primary: "#0050cb",
        "outline-variant": "#c2c6d8",
        "on-background": "#1a1b22",
        tertiary: "#a33200",
        "surface-bright": "#fbf8ff",
        "on-surface": "#1a1b22",
        "on-tertiary": "#ffffff",
        outline: "#727687",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary-fixed-variant": "#3f465c",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b3c5ff",
        surface: "#fbf8ff",
        "surface-container-highest": "#e3e1ec",
        "inverse-on-surface": "#f1effa",
        "surface-dim": "#dad9e3",
        "surface-container-high": "#e8e7f1",
        "tertiary-fixed-dim": "#ffb59d",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2f3038",
        "on-tertiary-container": "#fff6f4",
        "on-primary-container": "#f8f7ff",
        "on-primary-fixed-variant": "#003fa4",
        "on-tertiary-fixed-variant": "#832600",
        "secondary-fixed": "#dae2fd",
        "inverse-primary": "#b3c5ff",
        "secondary-container": "#dae2fd",
        "primary-container": "#0066ff",
        "on-secondary-container": "#5c647a",
        "on-tertiary-fixed": "#390c00",
        "surface-container": "#eeedf7",
        "primary-fixed": "#dae1ff",
        "surface-variant": "#e3e1ec",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#131b2e",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001849",
        "surface-tint": "#0054d6",
        "surface-container-low": "#f4f2fd",
        secondary: "#565e74",
        "tertiary-container": "#cc4204",
        error: "#ba1a1a",
        "tertiary-fixed": "#ffdbd0",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xl: "24px",
        xs: "4px",
        sm: "8px",
        md: "12px",
        gutter: "12px",
        unit: "4px",
        "container-margin": "20px",
        lg: "16px",
      },
      fontFamily: {
        "headline-sm": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "label-xs": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        display: ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-xs": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        display: ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        mono: ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
